version: '3'

services:
  sandbox:
    image: 'enqueue/dev:latest'
    entrypoint: '/entrypoint.sh'
    working_dir: '/mqs/symfony'
    restart: 'always'
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
    volumes:
      - ./docker/container/php/cli.ini:/etc/php/7.1/cli/conf.d/1-sandbox_cli.ini
      - ./docker/shared/:/shared
      - ./:/mqs
    env_file: 'symfony/app/config/.env'
    environment:
      - HISTFILE=/shared/.bash_history
    ports:
      - "80:80"

  sandbox_consumer:
    image: 'enqueue/dev:latest'
    entrypoint: 'php ./bin/console enqueue:consume --setup-broker -vvv'
    working_dir: '/mqs/symfony'
    restart: 'always'
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
    volumes:
      - ./docker/container/php/cli.ini:/etc/php/7.0/cli/conf.d/1-sandbox_cli.ini
      - ./docker/shared/:/shared
      - ./:/mqs
    env_file: 'symfony/app/config/.env'
    environment:
      - HISTFILE=/shared/.bash_history

  sandbox_laravel:
    image: 'enqueue/dev:latest'
    entrypoint: php artisan serve --host 0.0.0.0 --port=80 -vvv
    restart: 'always'
    working_dir: '/mqs/laravel'
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
    volumes:
      - ./docker/container/php/cli.ini:/etc/php/7.0/cli/conf.d/1-sandbox_cli.ini
      - ./docker/shared/:/shared
      - ./:/mqs
    env_file: 'laravel/.env'
    environment:
      - HISTFILE=/shared/.bash_history
    ports:
      - "81:80"

  mysql:
    image: mariadb:10
    restart: 'always'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mqs
    ports:
      - "3307:3306"

  rabbitmq:
    build: { context: ., dockerfile: Dockerfile.rabbitmq }
    restart: 'always'
    ports:
      - "15673:15672"
      - "15674:15674"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=mqs

  elasticsearch: 
    image: elasticsearch:2
    restart: 'always'
    ports: 
      - "9200:9200"

#  elasticsearch: 
#    image: elasticsearch:5
#    restart: 'always'
#    ports: 
#      - "9200:9200"

volumes:
  mysql-data:
    driver: local
